// <auto-generated />
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherLink.Models;

namespace WeatherLink.Migrations
{
    [DbContext(typeof(SlackWorkspaceAppContext))]
    partial class SlackWorkspaceAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("WeatherLink.WorkspaceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<string>("TeamId");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("WorkspaceTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
